// Montserrat Bold subset: digits 0-9, '.', '-'
// Generated by pyftsubset from Montserrat-Bold.ttf
#pragma once

#include <stddef.h>
#include <stdint.h>

extern const uint8_t montserrat_bold_digits_ttf[];
extern const size_t montserrat_bold_digits_ttf_len;
